spring:
  application:
    name: user-api
  datasource:
    url: jdbc:h2:mem:teste
    driver-class-name: org.h2.Driver
    username: admin
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      path: /h2
      enabled: true
server:
    port: 8000
