spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-api
          uri: lb://user-api
          predicates:
            - Path=/user/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET, POST
                statuses:
                  - INTERNAL_SERVER_ERROR
                  - BAD_GATEWAY
                  - SERVICE_UNAVAILABLE
                  - GATEWAY_TIMEOUT
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      retry:
        enabled: true
server:
  port: ${PORT:8765}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
