spring:
  application:
    name: eureka-server
server:
  port: ${PORT:8761}
eureka:
  instance:
    lease-renewal-interval-in-seconds: 0
  server:
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false